### ISSUE TITLE
Settings server not running after installation

### ISSUE THREAD

**Issue by vollstock** [vollstock/Tooloop-Settings-Server#21]
I received this report via mail:

> I go to Settings/System Settings and I get this
> ![screenshot 4 _edited](https://user-images.githubusercontent.com/4962676/47559700-79286b00-d916-11e8-8c93-ee892e2e9deb.jpg)

**Comment by vollstock** [comment]
The screenshot shows that the server is not running at all.

Please confirm by checking the status:

```
systemctl status tooloop-settings-server.service
```

To find out what’s gone wrong, please check the complete output of the server and see if you can see anything suspicious:

```
journalctl --unit tooloop-settings-server.service
```
(exit with ```q```)

You could also stop the system service and run the server manually to see what’s going on live:

```
sudo systemctl stop tooloop-settings-server.service
cd /opt/tooloop/settings-server/
sudo python tooloop-settings-server.py
```

**Comment by manuelpiepereit** [comment]
While trying to run the settings server, I'm getting the error that the config.cfg could not be found

```
File "tooloop-settings-server.py", line 32 in <module> app.config.from_pyfile('config.cfg') 
... 
(No such file or directory): '/opt/tooloop/settings-server/config.cfg' ...
```

Changed the path in python file to 'data/config.cfg' to get it back up.
Hope that helps.

**Comment by vollstock** [comment]
Thanks Manuel,
I have changed the past a while ago. No clue, why the change didn’t make it to a commit :-/
