### ISSUE TITLE
Getting correct ip address in system controller

### ISSUE THREAD

**Issue by oleprinds** [vollstock/Tooloop-Settings-Server#22]
On ubuntu 18.04.5 with the 'appcenter' branch I have noticed, that the settings server doesn't return the correct ip address. In my case it returns 127.0.0.1

In the system_controller.py, the get_ip() calls hostname with argument -i, but it doesn't always return the actual ip, since the -i argument relies on the hostname setup. And a machine with only localhost in /etc/hosts will return the localhost ip..

Using the -I argument however relies on the network settings to get the ip, which in my case returns the correct ip.

From the 'man hostname'
> -I, --all-ip-addresses
    Display all network addresses of the host. This option enumerates all
    configured  addresses  on all network interfaces. The loopback inter‐
    face and IPv6 link-local addresses are omitted.  Contrary  to  option
    -i,  this  option does not depend on name resolution. Do not make any
    assumptions about the order of the output.

There could be an issue, if a machine has multiple ip's setup, I'm not sure, how it would behave.. but in a typical installation setup, there is usually only one.

[hostname_argument_change.patch.txt](https://github.com/vollstock/Tooloop-Settings-Server/files/5957496/hostname_argument_change.patch.txt)

**Comment by vollstock** [comment]
fixed by pull request #23
